server:
  port: 9999
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: ${SPRING_DATASOURCE_URL}
    password: ${DB_ELAMA_QUIZ_PASSWORD}
    username: ${DB_ELAMA_QUIZ_USERNAME}
    hikari:
      connection-timeout: 100000
      idle-timeout: 600000
      max-lifetime: 1800000
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
    enabled: false
  sql:
    init:
      continue-on-error: true
  thymeleaf:
    enabled: true
    prefix: "classpath:/static/"
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}